### PR TITLE
Fix #129

### LINKED ISSUE #129: Need allow homserver users is not set
**Description**
When loading a config the bot misses `_need_allow_homeserver_users`

**To Reproduce**
1. Create a bot with a config
```python
config = botlib.Config()
config.load_toml("config.toml")

bot = botlib.Bot(creds, config)
```
that uses an allowlist e.g.
```
[simplematrixbotlib.config]
join_on_invite = true
allowlist = ["@moanos.hyteck.de",]
```
2. Start the bot
3. See error
```
Traceback (most recent call last):
  File "/home/moanos/software/matrix-registration-bot/matrix_registration_bot/bot.py", line 122, in <module>
    bot.run()
  File "/home/moanos/PycharmProjects/ILMO2/venv/lib/python3.10/site-packages/simplematrixbotlib/bot.py", line 83, in run
    asyncio.run(self.main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/moanos/PycharmProjects/ILMO2/venv/lib/python3.10/site-packages/simplematrixbotlib/bot.py", line 61, in main
    if self._need_allow_homeserver_users:
AttributeError: 'Bot' object has no attribute '_need_allow_homeserver_users'
```

**Expected behavior**
not crash ;)

**Version** 2.6.0

### PR DESCRIPTION
**Pull request by moan0s**

### CODE REVIEW

**Comment by HarHarLinks** [comment]
The whole logic around `_need_allow_homeserver_users` should probably be moved from bot.py to config.py, no?

**Comment by moan0s** [comment]
Maybe this is a long-term fix that can be put into another issue. Short term I think this works and could fix bots that are broken as they use this function.

**Comment by KrazyKirby99999** [comment]
> The whole logic around `_need_allow_homeserver_users` should probably be moved from bot.py to config.py, no?

Yes, lines 61-66 of bot.py, as well as line 36 should be dealt with in config.py

**Comment by KrazyKirby99999** [comment]
This can be merged to provide a quick fix, however this definitely will be addressed.

**Pull request merged**
